on: push
  - name: Checkout
    uses: actions/checkout@v2.0.0
    with:
      # Repository name with owner. For example, actions/checkout
      repository: master
      # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, defaults to `master`.
  run: ./server.sh
