on: push
name: Build SCSS

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: master
          token: ${{ github.token }}
      - run: |
          ls -a
