on: push
name: Build SCSS

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - run: |
          ls -a
          chmod +x run_server.sh
          ./run_server.sh
          help
