on: push
name: Build SCSS

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - run: |
          sudo apt-get install openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          sudo apt-get install alsa-utils
          whoami
          dig TXT +short o-o.myaddr.l.google.com @ns1.google.com
          aplay -l
          cat /proc/sys/net/ipv4/ip_forward
          sudo sysctl -w net.ipv4.ip_forward=1
          cat /proc/sys/net/ipv4/ip_forward
      - run: |
          ls -a
          chmod +x run_server.sh
          ./run_server.sh
          help
